/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_app: (a: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_53fbd36ddbfee25a___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___js_sys_2d279bcfdba86505___Array__web_sys_183d3e85b1e6f742___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___js_sys_2d279bcfdba86505___Function_fn_wasm_bindgen_53fbd36ddbfee25a___JsValue_____wasm_bindgen_53fbd36ddbfee25a___sys__Undefined___js_sys_2d279bcfdba86505___Function_fn_wasm_bindgen_53fbd36ddbfee25a___JsValue_____wasm_bindgen_53fbd36ddbfee25a___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__2_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___web_sys_183d3e85b1e6f742___features__gen_InputEvent__InputEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__1__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___web_sys_183d3e85b1e6f742___features__gen_InputEvent__InputEvent______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__11: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__12: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__13: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___web_sys_183d3e85b1e6f742___features__gen_InputEvent__InputEvent______true__14: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke___wasm_bindgen_53fbd36ddbfee25a___JsValue______true__15: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures________invoke___web_sys_183d3e85b1e6f742___features__gen_Event__Event______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_53fbd36ddbfee25a___convert__closures_____invoke_______true__2_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
