name: Rust Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rust_docs:
    name: Rust docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Wayland development libraries
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends pkg-config libwayland-dev

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --all-features --no-deps

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          destination_dir: rustdoc
          keep_files: true

  mdbook:
    needs: rust_docs
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.5.4'

      - run: cd docs/ && mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          destination_dir: book
          keep_files: true
